### ISSUE TITLE
store binary datafile in data folder

### ISSUE THREAD

**Issue by jknockaert** [michelbierlaire/biogeme#1]
Pythonbiogeme creates a binary datafile before the model is estimated. The binary file is however stored in the folder where the model file is, rather than where the original datafile is found. In some cases you may want to write a wrapper script that copies a (compressed) datafile from a network drive to a local tmp folder (and uncompress it there) before running a batch of model estimations which are on the network drive; this in order to reduce network bandwith usage. So it seems more appropriate to me to store the binary datafile in the same place where pythonbiogeme finds the input dataset.

**Comment by michelbierlaire** [comment]
The current version of Biogeme does not create this binary file anymore. Indeed, the responsibility of data management is transferred to Pandas.
