### ISSUE TITLE
possible versions issue between numpy, scipy, biogeme depedencies

### ISSUE THREAD

**Issue by mherkazandjian** [michelbierlaire/biogeme#25]
Hi,

I ran into this issue on using biogeme on google colab (vanilla environment / runtime).

the following fails

```
pip install biogeme
import biogeme.biogeme as bio
from biogeme import models
from biogeme.expressions import Beta
```
with the following error

![image](https://github.com/michelbierlaire/biogeme/assets/3264637/f779676a-5734-40f3-9013-0edc8cae437c)

however, specifying the versions as such solves the problem.

```
!pip install numpy==1.24.2
!pip install scipy==1.11.2
!pip install biogeme==3.2.12
```

maybe the version can be set stricter in the setup.cfg file?

Best,

**Comment by michelbierlaire** [comment]
Did it happen again with the recent releases?
