### ISSUE TITLE
Clean up large distribution files

### ISSUE THREAD

**Issue by EwoutH** [michelbierlaire/biogeme#27]
Currently there are quite some large distribution files included in this repo, and a large .git history, making the repo almost 800 MB. Maybe some large, outdated files can be removed or de-duplicated. That would cloning and working on it easier.

![image](https://github.com/michelbierlaire/biogeme/assets/15776622/54788453-885e-49fd-b21b-308cc41442e3)

**Comment by EwoutH** [comment]
@michelbierlaire One option is to use [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) to upload the binaries to. Then they are publicly available, by release version, and don't take up space in the repo.

It can even be fully automated using CI. I can help set if up, if you want.

**Comment by michelbierlaire** [comment]
I have simply removed them. There is no need to keep this on GitHub.
