### ISSUE TITLE
Repository status

### ISSUE THREAD

**Issue by EwoutH** [michelbierlaire/biogeme#3]
@michelbierlaire First of all, thanks for making such a great software package! What's the status of this GitHub repository? Is it still in active development / maintenance?

I see regular updates of the [python package](https://pypi.org/project/biogeme/), it would be great to be able to contribute to those releases!

**Comment by michelbierlaire** [comment]
Thank you for your email. 

Yes, it is still in active development, although a brand new version has been developed and distributed. And I need to move the repository to the new version in a clean way. One of my PhD students will help me to do so, hopefully within the next month. 

What kind of contribution do you have in mind?

**Comment by EwoutH** [comment]
Thanks for your quick reply. Looking forward to the new repository!

At first, maybe some CI. Having the code open source will significantly shorten the feedback loop on bug reporting and let users debug on their own and even submit fixes.

**Comment by michelbierlaire** [comment]
It *is* open source. The source are available from pypi.org. 
It's just that I need to update the github repository.

**Comment by EwoutH** [comment]
Got it!

If you would like it I could setup a CI system that automatically deploys the package to Pypi when a Git tag or GitHub release is made (with [Travis CI](https://docs.travis-ci.com/user/deployment/pypi/) for example). That way the tags on Git and on Pypi will always be identical.

**Comment by EwoutH** [comment]
Thanks for updating the repository!
